### ISSUE TITLE
Change 'InterfacesRemoved' because convention is different

### ISSUE THREAD

**Issue by nschoe** [partnering/node-dbus#20]
I previously inferred that an empty array meant "this entire object should be removed", but after talking on #dbus and asking in the DBus mailing list, it turns out that this convention was not chosen, instead when removing an object, one should send the array with all the interfaces, and it's the proxy's responsibility to delete the object when all its interfaces have disappeared.

**Comment by nilpotence** [comment]
makes sense...

**Comment by nschoe** [comment]
Well actually, the people on #dbus told me that the way I had imagined it is the more elegant and _should_ have been the implemented way, but since the "reference" implementation of libgdbus doesn't do this, we can't make it work like that now :/

Anyway, fix is almost ready!

**Comment by nilpotence** [comment]
I don't see how this is more elegant. I think signaling all interfaces on object deletion is more homogenous regarding InterfacesRemoved's behavior. Sending a null array on object deletion looks like an exception to what InterfacesRemoved usually outputs.

Anyway, that's just a matter of opinion.

**Comment by nschoe** [comment]
Issue closed in branch DBusProxy
