### ISSUE TITLE
[p1.1.2] cannot subscribe to the changes of a struct property

### ISSUE THREAD

**Issue by VictorDubois** [partnering/node-dbus#22]
This does not send "PropertiesChanged" signal:
```
DBusProperty (Neuralizer, 'Progress', {
	read: t.DBUS_STRUCT (t.DBUS_STRING, t.DBUS_STRING, t.DBUS_UINT16)
})
```

while this does:
```
DBusProperty (Neuralizer, 'Progress', {
	read: t.DBUS_STRING
})
```

Tested with gdbus monitor, and by modifying the struct in various ways.

**Comment by nschoe** [comment]
This appears to be true for array too.
I suspect this is true for all containers type... :/

**Comment by nschoe** [comment]
Issue closed in branch DBusProxy
