### ISSUE TITLE
'ExposedOnBus' is not called when dynamically adding objects

### ISSUE THREAD

**Issue by nilpotence** [partnering/node-dbus#9]
Does it make sense to fire a ```ExposedOnBus``` on each dbus object creation ? or just for the main object ?

**Comment by nilpotence** [comment]
This is due to the fact that ExposedOnBus signal is emitted in the bus.exposeService method.
It also implies that when adding object paths dynamically after the initial invokation of the exposeService method, property getters/setters are not set properly and therefore the PropertiesChanged signal is not fired on property change on these objects.

**Comment by nschoe** [comment]
I think you solved this in PR #11, right? In which case, can include include a "fix #9" message in your commit message?

**Comment by nilpotence** [comment]
That's right.

**Comment by nschoe** [comment]
Closed in branch DBusProxy
